# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='opinion_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='truth',
            name='truth_text',
            field=models.TextField(),
        ),
    ]
