# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
