# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='title_text',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
